# Generated by Django 5.0.4 on 2024-04-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0006_remove_cancel_id_alter_cancel_wedding_party_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingservice',
            name='quantity',
        ),
    ]
