# Generated by Django 5.0.4 on 2024-04-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0007_remove_weddingservice_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingparty',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weddingparty',
            name='shift_party',
            field=models.CharField(choices=[('MORNING', 'MORNING'), ('AFTERNOON', 'AFTERNOON'), ('EVENING', 'EVENING')], default='MORNING', max_length=255),
        ),
    ]
