# Generated by Django 5.0.4 on 2024-05-02 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0009_remove_cancel_employee_id_cancel_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancel',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancel_employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='wedding/user'),
        ),
    ]
