# Generated by Django 5.0.4 on 2024-05-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0011_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddinghall',
            name='description',
        ),
        migrations.AddField(
            model_name='weddinghall',
            name='description_text',
            field=models.TextField(null=True),
        ),
    ]
