# Generated by Django 5.0.4 on 2024-04-12 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_alter_category_id_alter_menu_id_alter_menu_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_date', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.IntegerField()),
                ('wedding_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_party', to='wedding.weddingparty')),
            ],
        ),
    ]
