# Generated by Django 5.0.4 on 2024-04-12 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 15, 41, 52, 892763)),
        ),
        migrations.AddField(
            model_name='menu',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 15, 41, 52, 892763)),
        ),
        migrations.AddField(
            model_name='service',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 15, 41, 52, 892763)),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 15, 41, 52, 892763)),
        ),
    ]
