# Generated by Django 5.0.4 on 2024-04-15 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0005_alter_menu_created_date_alter_menu_updated_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancel',
            name='id',
        ),
        migrations.AlterField(
            model_name='cancel',
            name='wedding_party',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wedding.weddingparty'),
        ),
        migrations.AlterField(
            model_name='weddinghall',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
